<?php include 'cabecalho.php';?>

      <div id="producao" class="col s8">
        <div id="menor">
          <div id="titulo">
            <h4 class="center-align black-text" style="font-family: Satisfy;">Escrita como Processo</h4>
            <h6 class="black-text" style="line-height: 21px;">&emsp;&emsp;&emsp;&emsp;O texto escrito não é uma atividade solitária, como já se propagou por algum tempo. Koch (1997, p. 22) defende a posição de que a produção textual é:<br>
              a) Uma atividade verbal, a serviço de fins sociais e, portanto, inserida em contextos mais complexos de atividades;<br>
              b) Que se trata de uma atividade consciente, criativa, que compreende o desenvolvimento de estratégias concretas de ação e a escolha de meios adequados à realização dos objetivos, isto é, trata-se de uma atividade intencional que o falante, de conformidade com as condições sob as quais o texto é produzido, empreende, tentando dar a entender seus propósitos ao destinatário através da manifestação verbal;<br>
              c) É uma atividade interacional, visto que os interlocutores, de maneiras diversas, se acham envolvidos na atividade de produção textual.<br>
              &emsp;&emsp;&emsp;&emsp;Os estudos mostram que a produção textual deve ser uma atividade organizada em quatro níveis de operações: o planejamento, a textualidade, a revisão e a reescrita ou refacção. O planejamento é o pré-requisito de todo o trabalho. Supõe o emprego de capacidades cognitivas gerais e variadas entre os polos da seleção e organização das ideias. A textualização agrupa todas as operações de determinação e estruturação propriamente linguísticas da etapa de planejamento. A revisão que propicia o reexame crítico do texto produzido e a possibilidade de modificações, levando a operações de adequação definitiva. Finalmente, a essa possibilidade de modificações e adequação definitiva, nós damos o nome de reescrita ou refacção do texto. Assim, você refaz o texto, dando a legibilidade necessária para que seu destinatário construa sentidos para o que você escreveu. Quem já não precisou “passar a limpo” algum texto? É justamente essa prática que dá legibilidade ao texto, sem necessariamente passar pelo processo de “higienização” que consiste em eliminar os “erros gramaticais” e analisar o texto apenas no nível da transgressão da norma. Essa higienização é feita pelos professores, ao corrigirem os textos escolares, detendo-se apenas a apontar “erros” de superfície linguística, ou seja, de ordem gramatical.<br>
              &emsp;&emsp;&emsp;&emsp;Ao construir um texto, o escritor faz uso de diferentes tipos de conhecimentos e produz textos para interagir com outros indivíduos dentro de determinados contextos sociais. Além disso, ao interagir com outros indivíduos, o escritor faz também uso de conhecimentos sobre mecanismos de interação. Desta forma, ao vivenciar o processo de escrita, o escritor observa que escrever não é resultado de uma inspiração divina, mas que para escrever adequadamente, conforme propósitos definidos, quem escreve constrói os sentidos necessários para aquilo que quer enunciar. Por isso, ele deve ler e reler o que escreveu, organizar e reorganizar as ideias, identificar os problemas gramaticais e compor o texto, de modo que corresponda aos objetivos iniciais.<br>
            </h6>
          </div>

          <div id="introducao">
            <h4 class="center-align black-text" style="font-family: Satisfy;">A Revisão e a Reescrita</h4>
            <h6 class="black-text" style="line-height: 21px;">&emsp;&emsp;&emsp;&emsp;A noção de escrita na perspectiva de produto cria no escritor uma visão limitada sobre o ato de escrever, tendo em vista que o texto passa a ser julgado e avaliado, levando em consideração, em geral, aspectos formais linguísticos e características superficiais. As avaliações são feitas mais em termos de sentenças do que de conteúdos. Ao escrevente é negada a possibilidade de revisar o texto e reescrevê-lo, principalmente, em sala de aula.<br>
              &emsp;&emsp;&emsp;&emsp;Nesse caso, o professor se coloca, como um juiz implacável, que dita comportamentos linguísticos, sem considerar a intenção de quem escreveu e a relação com seu destinatário. Na escrita como processo, o foco não é o texto como produto final, mas o processo, que deve levar em consideração a situação da enunciação e as condições discursivas que são determinantes na função da linguagem, de seu significado e de sua interpretação. Quem escreve deve ter clareza sobre seus objetivos, de sua audiência e da necessidade de interagir com seu destinatário para que ele construa significados. Além do mais, nessa visão, o texto é produzido imerso numa situação social de produção definida.<br>
              &emsp;&emsp;&emsp;&emsp;Essa concepção enfatiza a importância da revisão, investido no potencial do escritor e no sucesso da reescrita, que permite ao escritor um redirecionamento de suas ideias. A escrita é vista numa perspectiva global, efetivando mudanças que reordenam o todo ou atingem segmentos do discurso. Dessa forma, a escrita é uma construção que se processa na interação e a revisão é um momento que demonstra a vitalidade desse processo construtivo.<br>
              &emsp;&emsp;&emsp;&emsp;Assim, o ato de escrever, como já afirmamos em aulas anteriores, deixa de ser considerado um “dom” e passa a ser concebido como uma produção textual, que exige trabalho, e não, inspiração. Uma aprendizagem, por meio do trabalho da reescrita, demonstra a dimensão das múltiplas possibilidades de realização da linguagem, resultado do texto original e dos textos dele decorrentes. A revisão e a reescrita do texto são alternativas que poderão ser bem sucedidas, contrapondo-se às formas mais tradicionais de redação escolar, cujo resultado poderá ser visto como uma matriz de problemas e soluções. Produzir textos, seguindo essa orientação é estar aberto a operações de autocorreção, tais como substituição, apagamento, deslocamento e acréscimo.<br>
              Ao revisar um texto, podemos substituir termos, insistentemente usados, por outros, que se adequem melhor ao contexto de produção. Podemos, também, apagar ou deletar termos que decidimos retirar do texto para melhorar o sentido dos enunciados. Podemos, ainda, deslocar termos que por alguma razão não devem estar naquele local e, finalmente, podemos acrescentar termos para ampliar nossas ideias, dando maior consistência ao que queremos enunciar.<br>
              &emsp;&emsp;&emsp;&emsp;Como afirma Garcez (2002), na produção de textos há idas e vindas e todas essas ações estão profundamente articuladas ao contexto em que se originou e em que acontece a produção.<br>
              &emsp;&emsp;&emsp;&emsp;Para tanto, essa autora recomenda que nesse processo é preciso enfatizar as ideias principais, reordenar as informações, substituir ideias inadequadas, eliminar ideias desnecessárias, alcançar maior exatidão para as ideias, acrescentar exemplos, conceitos, citações, argumentos,  eliminar incoerências, estabelecer hierarquia entre as ideias e criar vínculos entre uma ideia e outra (GARCEZ, 2002, p. 18).<br>
              &emsp;&emsp;&emsp;&emsp;Como você deve ter percebido, escrever exige esforço, disciplina, atenção e paciência. Ninguém escreve por simples inspiração e todo bom produtor de texto deve procurar rever sua primeira versão para depois de muitas releituras e reescritas, escrever a versão definitiva.<br>
              &emsp;&emsp;&emsp;&emsp;No trabalho com a produção de textos, é importante destacar que a criação e a articulação de espaços de interlocução são fundamentais como condição para o processo de produção textual. Nesse processo, o aluno precisa vivenciar ou supor situações significativas de linguagem e, em função dessas situações, escolher os recursos linguístico-discursivos necessários à composição textual. Sendo assim, é bom lembrar que nesse trabalho é preciso oportunizar situações de escrita como uma prática social. Para isso, faz-se necessário possibilitar a produção de diversos gêneros textuais, levando em consideração as condições de produção e tendo em vista que o escritor deve usar os procedimentos de planejamento, escrita, revisão e reescrita.<br><br>
              GARCEZ, L. H. do. Técnica de redação: o que é preciso saber para bem escrever. São Paulo: Martins Fontes, 2002.</h6>
            </div>

          </div>
        </div>

<?php include 'rodape.php';?>