<?php include 'cabecalho.php';?>

      <div id="producao" class="col s8">
       <div id="menor">
        <div id="tessitura">
         <h4 class="center-align black-text" style="font-family: Satisfy;">Tessitura Textual: O Processo de Construção de um Texto</h4>
         <h6 class="black-text" style="line-height: 21px;">&emsp;&emsp;&emsp;&emsp;Sempre que alguém escreve, há uma expectativa de que o texto produzido espelhe as maneiras de falar ou escrever das diferentes instituições que regulam a comunidade onde o indivíduo esta inserido. Espera-se, portanto, que todos os textos tenham formas, funções e conteúdos específicos, que necessariamente estejam imbricados com os discursos.<br>
          &emsp;&emsp;&emsp;&emsp;Que são, então, texto e discurso? Etimologicamente, texto significa tecido. Do ponto de vista linguístico, texto é “[...] qualquer passagem falada ou escrita, que forma um todo significado, independente de sua extensão” (FÁVERO e KOCK, 1983, p. 25). Garcez (1998, p. 66) conceitua texto como...<br>
          <blockquote><h6 class="black-text" style="line-height: 21px;">Uma unidade linguística, um exemplar concreto e único, o produto material de uma ação verbal, que se caracteriza por uma organização de elementos ligados entre si, segundo regras coesivas que asseguram a transmissão de uma mensagem de forma coerente.</h6></blockquote>
          &emsp;&emsp;&emsp;&emsp;Mas para a realização do texto é preciso que esse “todo significativo” seja produzido num espaço e num tempo determinados. O texto é, pois, “um evento dialógico, de interação entre sujeitos sociais, contemporâneos ou não, co-presentes ou não, do mesmo grupo social ou não, mas em diálogo constante” (KOCK, 2003, p. 20 ). O texto pode ser entendido, ainda, em seu sentido amplo como o resultado da história sócio-cultural do escritor e do leitor, considerando-o como um processo que se efetiva sócio-histórico e culturalmente. Convivemos, portanto, com uma diversidade de textos verbais e não-verbais, como uma foto, uma pintura, uma escultura, um filme, uma dança, entre outros.<br>
          &emsp;&emsp;&emsp;&emsp;Nesse sentido, um texto não é um amontoado de palavras. Mas sim, um fenômeno linguístico, complexo, que se inscreve num contexto social, ideológico e dialógico, perpassado pelos enunciados de um autor e por todos os outros enunciados que o compõe, formando um “tecido”, advindo dos fios dialógico/ideológico. Com base nessa perspectiva, destacamos que...<br>
          <blockquote><h6 class="black-text" style="line-height: 21px;">Na composição de quase todo enunciado do homem social – desde a curta réplica do diálogo familiar até as grandes obras verbal-ideológicas (literárias, científicas e outras) existe, numa forma aberta ou velada, uma parte considerável de palavras significativas de outrem, transmitidas por um outro processo. BAKHTIN, 1975, p. 153.</h6></blockquote>
          &emsp;&emsp;&emsp;&emsp;Compor um texto significa, assim, a realização de enunciados concretos numa dada esfera da comunicação humana. E sendo assim, consiste o ponto central na constituição dos textos, pois quando produzimos linguagem (oral ou escrita) estamos produzindo enunciados concretos, formatados em gêneros, que discutiremos mais adiante.<br>
          &emsp;&emsp;&emsp;&emsp;Os textos/enunciados que produzimos são, então, perpassados por outros enunciados que precederam, formando uma cadeia muito complexa de tantos outros enunciados/ discursos produzidos num tempo social e histórico. São, portanto, manifestações que articuladas, por meio da linguagem, veiculam valores, integram pontos de vista, avaliações, acentos e significados de um grupo social.<br>
          &emsp;&emsp;&emsp;&emsp;Os enunciados formam a cadeia discursiva, pois “o discurso nasce no diálogo como sua réplica viva, forma-se na mútua-orientação dialógica do discurso de outrem no interior do objeto’ (BAKHTIN, 1975, p. 89). Nessa relação dialógica, o sujeito constitui seu discurso, uma resposta a outros discursos já ditos e não-ditos, seja numa situação imediata, seja num contexto mais amplo. A palavra/enunciado é o signo ideológico por natureza de toda elaboração discursiva e nela subjaz uma formação ideológica. Nesta direção, pode-se afirmar que não existem discursos neutros. Todo discurso é orientado para uma resposta, que refuta, pergunta, discorda, concorda, por que “a linguagem é grandemente pluri discursiva” (BAKHTIN, 1975, p. 98).<br>
          &emsp;&emsp;&emsp;&emsp;A aprendizagem da escrita passa a ser vista como um processo que se realiza com a participação ativa do outro. No dizer de Garcez (1998, p. 42)<br>
          <blockquote><h6 class="black-text" style="line-height: 21px;">É pela via da reflexão das práticas interativas sobre a escrita no universo escolar que o paradigma cognitivista começa a ser superado, dando lugar às reflexões socioconstrutivistas e sociointeracionistas.</h6></blockquote>
          &emsp;&emsp;&emsp;&emsp;O “outro” tem, portanto, vários papéis nesse processo:<br>
          &emsp;&emsp;&emsp;&emsp;- É parceiro no diálogo (mesmo a distância), e assim determina sua configuração;<br>
          &emsp;&emsp;&emsp;&emsp;- Permite que o eu se constitua como enunciador e compreenda sua própria enunciação, a partir da possibilidade de compreensão do outro;<br>
          &emsp;&emsp;&emsp;&emsp; - É o fornecedor da matéria-prima do discurso: qualquer discurso tem na sua origem outras palavras e outras vozes que não a do locutor.<br>
          &emsp;&emsp;&emsp;&emsp;A busca da compreensão, a necessidade de ser compreendido e o caráter dialógico intrínseco ao enunciado fazem com que o sujeito que enuncia constitua para si um possível destinatário, e de certa forma, se constitua também, transitoriamente como esse possível destinatário num processo dinâmico e complexo de inserção na rede comunicativa que se estabelece no sistema social.<br>
          &emsp;&emsp;&emsp;&emsp;Assim, o texto escrito, enquanto atividade significativa, constitui uma forma de relação dialógica que ultrapassa as meras relações linguísticas. É, portanto, uma unidade discursiva, significativa, que tem articulações com outras esferas de valores.<br>
          &emsp;&emsp;&emsp;&emsp;Qualquer usuário da língua quando produz um texto faz uso de uma linguagem social, pertencente a um grupo social particular e para isso faz uso, de gêneros textuais ou discursivos, conforme a esfera de produção da linguagem.<br>
          &emsp;&emsp;&emsp;&emsp;Assim, a atividade de escrever um gênero textual (carta, artigo científico, depoimento, tese, memorial, entre outros), para muitas pessoas pode ser uma experiência agradável, mas para outras pode ser muito difícil, conflitante e momento de muita tensão. Toda pessoa que escreve está inscrita numa prática social, em que deve escolher o que, como, onde, quando e por que vai produzir um gênero textual. Trata-se, muitas vezes, de um dilema que poderá ser solucionado à medida que compreendermos que só escrevemos quando temos finalidades sociais para usar a escrita, pois é assim que ela existe. Produzir um gênero só é possível quando temos razões para escrever, quando sabemos para quem devemos escrever e para onde vai a nossa escrita.<br><br>
          BAKHTIN, M. <b>Estética da criação verbal.</b> São Paulo: Martins Fontes, 1979.<br><br>
          <b> Questões de Literatura e de Estética:</b> a teoria do romance. São Paulo: UNESP, 1979.<br><br>
          FÁVERO, L. L. e KOCH, I. <b>Lingüística Textual:</b> Introdução. São Paulo: Cortez, 1983.<br><br>
          GARCEZ, L H. do C. <b>A escrita e o outro:</b> os modos de participação na construção do texto. Brasília: UnB, 1998.<br><br>
          <b> Técnica de redação:</b> o que é preciso saber para bem escrever. São Paulo: Martins Fontes, 2002.<br><br>
          KOCH, I. G. V. <b>Desvendando os segredos do texto.</b> São Paulo: Cortez, 2003.
        </h6>
      </div>

    </div>
  </div>

<?php include 'rodape.php';?>